### ISSUE TITLE
Adding API keys to the setup of the box

### ISSUE THREAD

**Issue by timmarschall** [austintrose/sigmapi-web#9]
Currently it is impossible to run the page locally because the keys are missing locally. We need a way to make this happen so we can develop in peace!

**Comment by austintrose** [comment]
The API keys for the calendar, you mean?

**Comment by timmarschall** [comment]
Yessir @austintrose

**Comment by timmarschall** [comment]
i can reproduce this.

setup on my small laptop yesterday. Same issue

**Comment by austintrose** [comment]
@timmarschall What we need is "fixture data" - some initial stuff for the database in dev, instead of starting on empty. Here's more info: https://docs.djangoproject.com/en/1.8/howto/initial-data/

I encourage you to add some and open up a PR.

**Comment by timmarschall** [comment]
YAYAYYAYAYAYAYYAY
